/// <reference lib="webworker" />
declare let self: ServiceWorkerGlobalScope;

import { precacheAndRoute } from 'workbox-precaching';

// Use the precache manifest generated by Workbox
precacheAndRoute(self.__WB_MANIFEST || []);

self.addEventListener('push', (event) => {
  console.log('Push message received:', event);
  const data = event.data?.json() || {};
  const title = data.title || 'StatTracker';
  const options = {
    body: data.body || 'You have a new notification.',
    icon: '/pwa-192x192.png',
    badge: '/favicon.svg',
    data: data.url || '/'
  };
  event.waitUntil(self.registration.showNotification(title, options));
});

self.addEventListener('notificationclick', (event) => {
  console.log('Notification click received.');
  event.notification.close();
  event.waitUntil(self.clients.openWindow(event.notification.data || '/'));
});
